### PR TITLE
add icon and reformat

### PR DESCRIPTION
**Pull request by daniel-feldman-ai**
image

### CODE REVIEW

**Review by sren-applied — APPROVED** [review]
ok fine

**Comment by jamison-lahman-ai** [comment]
Seems technically illegal?

**Review by sren-applied — CHANGES_REQUESTED** [review]
jk

**Comment by daniel-feldman-ai** [comment]
Illegal?!

**Comment by jamison-lahman-ai** [comment]
> Illegal?!

idk how that works man. I'd imagine one would need explicit consent to use the logo in this fashion since this is technically not endorsed by Applied?

**Review by sren-applied — APPROVED** [review]

**Comment by daniel-feldman-ai** [comment]
@sren-applied only you can merge

**Comment by sren-applied** [comment]
oops

**Pull request merged**
